# Generated by Django 3.2.5 on 2025-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatnefthistory',
            name='event',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ww2event',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
